
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build -t gwenko/portfolio .

      - name: Push image
        run: |
          docker login -u gwenko -p ${{secrets.REGISTRY_PASS}},
          docker push gwenko/portfolio